# Required
version: 2
formats: []

# Build documentation in the docs/ directory with mkdocs
mkdocs:
   configuration: mkdocs.yml

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  apt_packages:
    - libsndfile1-dev

# Optionally declare the Python requirements required to build your docs
  jobs:
    post_install:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
